{% set name = "zopfli" %}
{% set version = "0.4.0" %}
{% set bundle = "tar.gz" %}
{% set hash = "a8ee992b2549e090cd3f0178bf606dd41a29e0613a04cdf5054224662c72dce6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.{{ bundle }}
  sha256: {{ hash }}

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - {{ stdlib("c") }}
    - {{ compiler("c") }}
    - {{ compiler("cxx") }}
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
  host:
    - python
    - pip
    - setuptools
    - setuptools_scm
  run:
    - python

test:
  imports:
    - zopfli
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/obp/zopfli
  license_file: COPYING
  license: Apache-2.0
  license_family: Apache
  summary: Zopfli module for python
  dev_url: https://github.com/obp/zopfli

extra:
  recipe-maintainers:
    - jakirkham
