{% set name = "zopfli" %}
{% set version = "0.2.2" %}
{% set bundle = "zip" %}
{% set hash = "2d49db7540d9991976af464ebc1b9ed12988c04d90691bcb51dc4a373a9e2afc" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.{{ bundle }}
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.{{ bundle }}
  sha256: {{ hash }}

build:
  number: 1
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - python
    - pip
    - setuptools_scm
  run:
    - python

test:
  imports:
    - zopfli
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/obp/zopfli
  license_file: COPYING
  license: Apache-2.0
  license_family: Apache
  summary: Zopfli module for python
  dev_url: https://github.com/obp/zopfli

extra:
  recipe-maintainers:
    - jakirkham
