{% set name = "zopfli" %}
{% set version = "0.1.9" %}
{% set bundle = "zip" %}
{% set hash = "78de3cc08a8efaa8013d61528907d91ac4d6cc014ffd8a41cc10ee75e9e60d7b" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.{{ bundle }}
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.{{ bundle }}
  sha256: {{ hash }}

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - pip
  run:
    - python

test:
  imports:
    - zopfli

about:
  home: https://github.com/obp/zopfli
  license_file: COPYING
  license: Apache-2.0
  license_family: Apache
  summary: Zopfli module for python
  dev_url: https://github.com/obp/zopfli

extra:
  recipe-maintainers:
    - jakirkham
    - pmlandwehr
