{% set name = "zopfli" %}
{% set version = "0.2.3.post1" %}
{% set bundle = "zip" %}
{% set hash = "96484dc0f48be1c5d7ae9f38ed1ce41e3675fd506b27c11a6607f14b49101e99" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ hash }}

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - {{ stdlib("c") }}
    - {{ compiler("c") }}
    - {{ compiler("cxx") }}
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
  host:
    - python
    - pip
    - setuptools
    - setuptools_scm
  run:
    - python

test:
  imports:
    - zopfli
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/obp/zopfli
  license_file: COPYING
  license: Apache-2.0
  license_family: Apache
  summary: Zopfli module for python
  dev_url: https://github.com/obp/zopfli

extra:
  recipe-maintainers:
    - jakirkham
