appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: HzJGGZBBeHhDat3mPK1A74kHPwrN583qGooesV7HJmB3k59ActmWCwU5ro3LQcgaMjyN56r4kWMM2eI7OyYr/9yMMVRShwGL4esMr0cm3gOeh7KOIRXpWb3JrkUKjJNKHgoDqSkGMPzaVPdYccB5d2yYV2T6IM3cyQii83bPXjr5Ypu18pj64lt7ETMDo+scBjgfCYL9too0AfBfwIp91K2lf+M0XQlXRhQzszeKhyPZXDM+SDZNAMHRmVUJQS84vn0gl2EwZP3tvRJu5HVGvyxIism+9HMuJLHJYU4sSuFdAowKhHQSu/UfRjef6KCzfEVJ6EGL5x+Yyohn8QrXSzxngkJVTVqg+7EMn2ziyh1Qf5Zs5cst7mkwgESkbcbPhC0q+o88Vi56D+RpbXhryZXu3c6tmMMmgnC2t+W5uQZRanoiQL3TauED9M+HggdtJHN7SZeVXhxELbz6K+arDM5EqkNtB1V7nQpDyVoEBUZHIOIU65KF9suYKzQ7n0XUovmDBEd/D7CfQnKws1pKVPTjS60gIyBMQ02IvwLgGlStqX1HtdluLOL5PVMfd+X856NWwh9pbRT6bzVSdxDQieU3PuTPDon5mQIuF+aSK/of7+hUjhn80HdZgZrkIcGcn6+/fAtb5YjoMvMRfP9yhWfV+OkrRULbt6Yz4KRRuoc=}
